### ISSUE TITLE
Problem after installisation

### ISSUE THREAD

**Issue by sinder38** [tengattack/grafana-jsform-panel#1]
Hello, i have a problem with installation, on Grafana 7.5.0. "An unexpected error happened" appears after choosing panel visualization.

**Comment by tengattack** [comment]
It works with Grafana v6.7.4 currently, i will test it in v7.5.0 later

**Comment by sinder38** [comment]
ty

**Comment by tengattack** [comment]
fix grafana 7.x support in https://github.com/tengattack/grafana-jsform-panel/commit/54bfa8b259d01f43a02401ea023ea99c995de92c

**Comment by sinder38** [comment]
It seems to be working on 7.5.5 :+1
